# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 041e2a65e9ea9d15b763abb9a6bea8bd50bad0ec6b4aab468cc4985094f59dd538ce901b157335d243b6936623e3192dd29b228aa3c1522a24070c54c768bf82

test:
  secret_key_base: 1041f74f1c48dadc18eac104b261592d02ffe901bbe295ed5da6545f68aea1d5a9f209092771c4d9e0ddf5dbb56d95656562bc760c35b388695081ab8e25b87b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
